version: '2'
services:
  web:
    container_name: 'fmda_frontend_prod'
    build: 
      context: .
      dockerfile: staging.Dockerfile
    restart: on-failure  
    ports:
      - '3033:3033'
    volumes:
      - '/telnet/volumes/fmda_file_uploads/corp_uploads:/src/app/public/corp_uploads'
      - '/telnet/volumes/fmda_file_uploads/event_uploads:/src/app/public/events_pics_uploads'
      - '/telnet/volumes/fmda_file_uploads/individual_passports_uploads:/src/app/public/ind_passport'
      - '/telnet/volumes/fmda_file_uploads/individual_uploads:/src/app/public/ind_uploads'
      - '/telnet/volumes/fmda_file_uploads/treasury_certificate_uploads:/src/app/public/treasuryCertificate_uploads'
      - '/telnet/volumes/fmda_file_uploads/academic_certificate_upload:/src/app/public/academic_certificate_upload'
      - '/telnet/volumes/fmda_file_uploads/other_professional_certificate_upload:/src/app/public/other_professional_certificate_upload'
     
  
   

